import java.math.*;

/*

How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

NOTE made this in a very lazy way lmao

*/

// 07/27/2018: 561475600 ns

class Problem029{
    public static void main(String[] args) {
        long startTime = System.nanoTime();

        //Start Code
        BigInteger[] array = new BigInteger[10000]; //as long as it's bigger than 100x100
        for(int i = 0; i < array.length; i++) array[i] = new BigInteger("0");
        int currentEmpty = 0;

        for(int i = 2; i <= 100; i++){
            for(int j= 2; j <= 100; j++){
                BigInteger n = new BigInteger(""+i).pow(j);
                if(!contains(array,n)){
                    array[currentEmpty] = n;
                    currentEmpty++;
                }
            }
        }

        int i = 0;
        while(!array[i].equals(new BigInteger("0"))) i++;
        System.out.println(i);
        //End Code

        long endTime   = System.nanoTime();
        long totalTime = endTime - startTime;
        System.out.println(totalTime);
    }

    static boolean contains(BigInteger[] a, BigInteger test){
        int length = a.length;
        for(int i = 0; i < length; i++) if(a[i].equals(test)) return true;
        return false;
    }
}
