/*

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

*/

// 07/29/2018: 12854904000 ns

class Problem044{
    public static void main(String[] args) {
        long startTime = System.nanoTime();

        //Start Code

        //Generate Pentagonal Numbers
        int[] pN = new int[5000];
        pN[1] = 1;
        int currentAdder = 4;
        for(int i = 2; i < pN.length; i++){
            pN[i] = pN[i-1]+currentAdder;
            currentAdder += 3;
        }

        //Loop through array
        int maxD = 99999999;
        for(int i = 1; i < pN.length-1; i++){
            for(int j = i+1; j < pN.length; j++){
                if(contains(pN[i]+pN[j],pN) && contains(pN[j]-pN[i],pN) && Math.abs(pN[j]-pN[i]) < maxD){
                    maxD = Math.abs(pN[j]-pN[i]);
                }
            }
        }
        System.out.println(maxD);

        //End Code
        long totalTime = System.nanoTime() - startTime;
        System.out.println(totalTime);

    }

    static boolean contains(int n, int[] pN){
        for(int i = 0; i < pN.length; i++) if(pN[i] == n) return true;
        return false;
    }

}
