/*

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

*/

// 07/29/2018: 1253006900 ns

class Problem045{
    public static void main(String[] args) {
        long startTime = System.nanoTime();

        //Create Arrays
        int length = 100000;
        int[] triNum = new int[length], penNum = new int[length], hexNum = new int[length];
        triNum[1] = 1;
        penNum[1] = 1;
        hexNum[1] = 1;

        int triAdder = 2, penAdder = 4, hexAdder = 5;
        for(int i = 2; i < length; i++){
            triNum[i] = triNum[i-1] + triAdder;
            penNum[i] = penNum[i-1] + penAdder;
            hexNum[i] = hexNum[i-1] + hexAdder;

            triAdder += 1;
            penAdder += 3;
            hexAdder += 4;
        }

        //Check for Duplicates
        outerloop:
        for(int i = 286; i < length; i++){
            for(int j = i; j > 0; j--){

                //If first two numbers are equal
                if(triNum[i] == penNum[j]){
                    for(int h = j; h > 0; h--){

                        //If all three numbers are equal
                        if(penNum[j] == hexNum[h]){
                            System.out.println(triNum[i]);
                            break outerloop;
                        }
                    }
                }
            }
        }
        //End Code

        long totalTime = System.nanoTime() - startTime;
        System.out.println(totalTime);
    }
}
